apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-06-15T19:41:45Z"
  generation: 1
  labels:
    app: hasher
  name: hasher
  namespace: default
  resourceVersion: "11138"
  uid: d2171454-fdde-4a67-90b6-1b7f5dfcda61
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hasher
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hasher
    spec:
      containers:
      - image: santiagortiiz/hasher
        imagePullPolicy: Always
        name: hasher
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-06-15T19:42:30Z"
    lastUpdateTime: "2022-06-15T19:42:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-06-15T19:41:45Z"
    lastUpdateTime: "2022-06-15T19:42:30Z"
    message: ReplicaSet "hasher-5fcdfc7f9d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
