apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-06-15T19:42:31Z"
  labels:
    app: redis
  name: redis
  namespace: default
  resourceVersion: "11141"
  uid: 459fb867-dd36-4f96-92ed-a66236e86d15
spec:
  clusterIP: 10.100.28.41
  clusterIPs:
  - 10.100.28.41
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
