apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-06-15T19:42:31Z"
  labels:
    app: rng
  name: rng
  namespace: default
  resourceVersion: "11145"
  uid: a2676c10-ee79-4a89-b1a8-54ab63eee60c
spec:
  clusterIP: 10.108.104.91
  clusterIPs:
  - 10.108.104.91
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rng
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
